### ISSUE TITLE
npm run build error - core 0.1.5

### ISSUE THREAD

**Issue by thim81** [boyney123/eventcatalog#138]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

> @eventcatalog/core@0.1.5 build
> next build && next export

warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Checking validity of types...
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/node by running:

	npm install --save-dev @types/node

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

Error: Command failed: cross-env PROJECT_DIR=/home/vsts/work/1/s/event-catalog npm run build
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Command.<anonymous> (/home/vsts/work/1/s/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:60:5)
    at Command.listener [as _actionHandler] (/home/vsts/work/1/s/event-catalog/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/home/vsts/work/1/s/event-catalog/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/home/vsts/work/1/s/event-catalog/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/home/vsts/work/1/s/event-catalog/node_modules/commander/index.js:1460:12)
    at Command.parse (/home/vsts/work/1/s/event-catalog/node_modules/commander/index.js:1292:10)
    at run (/home/vsts/work/1/s/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7)
    at Object.<anonymous> (/home/vsts/work/1/s/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:122:1) {

### Steps to reproduce

Do a clean install and try to run `npm run build`

### Expected behavior

Succesfully build event catalog

### Actual behavior

see the error in the description

### Your environment

- EventCatalog version used: 0.1.5
- Environment name and version (e.g. Chrome 89, Node.js 16.4): NodeJS 16.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.2 LTS

**Comment by thim81** [comment]
Since I had a event catalog running, it was missing a dependency

Steps that fixed it:
- removed the `node_modules`, `.eventcatalog-core`, `.next `folders
- removed `package-lock.json`
- added "@types/node" to by running: `npm install --save-dev @types/node`
- ran `npm install`
- ran successfully `npm run build`
