### ISSUE TITLE
Command failed: cross-env PROJECT_DIR='...' npm run build

### ISSUE THREAD

**Issue by cao-minh-duc** [boyney123/eventcatalog#450]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

```
npm run build 

> event-catalog@0.0.1 build
> eventcatalog build


> @eventcatalog/core@1.1.0 scripts:move-schema-for-download
> node scripts/move-schemas-for-download.js


> @eventcatalog/core@1.1.0 build
> next build && next export

info  - Linting and checking validity of types .Failed to compile.

../node_modules/types-ramda/es/index.d.ts:4453:22
Type error: Type parameter declaration expected.

  4451 |  * ```
  4452 |  */
> 4453 | export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
       |                      ^
  4454 | export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
  4455 | 
  4456 | 
info  - Linting and checking validity of types ..
Error: Command failed: cross-env PROJECT_DIR='...' npm run build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Command.<anonymous> (/workspace/social-weaver/docs/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:60:5)
    at Command.listener [as _actionHandler] (/workspace/social-weaver/docs/event-catalog/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/workspace/social-weaver/docs/event-catalog/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/workspace/social-weaver/docs/event-catalog/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/workspace/social-weaver/docs/event-catalog/node_modules/commander/index.js:1460:12)
    at Command.parse (/workspace/social-weaver/docs/event-catalog/node_modules/commander/index.js:1292:10)
    at run (/workspace/social-weaver/docs/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 148199,
  stdout: null,
  stderr: null
}
```

### Steps to reproduce

`npx @eventcatalog/create-eventcatalog@latest test-catalog
cd test-catalog
npm run build`

### Expected behavior

It would build complete the build step and not error.

### Actual behavior

It fails during the build stage

### Your environment

- EventCatalog version used: 1.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js v18.18.0, v16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.2 LTS

**Comment by bengisc** [comment]
Same problem here, I cannot build anymore, even with a former version.

**Comment by boyney123** [comment]
Ah thank you for raising this. @bengisc Thanks for providing a fix.

Looks like the TypeScript version was missed in the CLI tool to create new catalogs. Checked that from 4.4.4 to the same v5 version in the Catalog! Thanks!
